#! /usr/bin/env ruby

require "date"

date = DateTime.parse("2014-01-01 10:00:00")

5.times do |i|
  i += 20
  date += 10
  puts "Generating build ##{i}..."
  system %{script/build}
  system %{script/commit "Did some work and created build ##{i}" "#{date}"}
end
